### ISSUE TITLE
gcloud CLI typo?

### ISSUE THREAD

**Issue by bendory** [GoogleCloudPlatform/artifact-registry-python-tools#19]
The README says:
`gcloud alpha artifacts print-settings pypi`
but in my `gcloud` installation, `pypi` doesn't exist, I have `gcloud alpha artifacts print-settings python`.

I'd send you a quick PR to fix, but given that it's an `alpha` surface in `gcloud` IDK if you're intending to migrate to `pypi` or some such.

**Comment by di** [comment]
Looks like this was missed in #11, it should be `python`.

**Comment by brummetj** [comment]
im running this command but still gettin a `invalid repository type PYTHON` 

```
ERROR: (gcloud.alpha.artifacts.print-settings.python) Invalid repository type PYTHON. Valid type is PYPI.
```

But if i type pypi it doesn't work either :(

**Comment by di** [comment]
@brummetj Can you run `gcloud components update` and try again?

**Comment by brummetj** [comment]
@di I got the same error after updating the components

**Comment by di** [comment]
@brummetj What's the output of `gcloud --version` and `gcloud artifacts print-settings --help`?

**Comment by TaridaGeorge** [comment]
Same issue.

gcloud --version
Google Cloud SDK 352.0.0
alpha 2021.08.06
beta 2021.08.06
bq 2.0.70
core 2021.08.06
gsutil 4.66

```
NAME
    gcloud artifacts print-settings - print snippets to add to native tools
        settings files

SYNOPSIS
    gcloud artifacts print-settings COMMAND [GCLOUD_WIDE_FLAG ...]

DESCRIPTION
    The snippets provide a credentials placeholder and configurations to allow
    native tools to interact with Artifact Registry repositories.

EXAMPLES
    To print a snippet to add a repository to the Gradle build.gradle file for
    repository my-repo in the current project, run:

        $ gcloud artifacts print-settings gradle --repository=my-repo

    To print a snippet to add to the Maven pom.xml file for repository my-repo
    in the current project, run:

        $ gcloud artifacts print-settings mvn --repository=my-repo

    To print a snippet to add to the npm .npmrc file for repository my-repo in
    the current project, run:

        $ gcloud artifacts print-settings npm --repository=my-repo

    To print a snippet to add to the Python .pypirc and pip.comf files for
    repository my-repo in the current project, run:

        $ gcloud artifacts print-settings python --repository=my-repo

GCLOUD WIDE FLAGS
    These flags are available to all commands: --help.

    Run $ gcloud help for details.

COMMANDS
    COMMAND is one of the following:

     gradle
        Print a snippet to add a repository to the Gradle build.gradle file.

     mvn
        Print a snippet to add a Maven repository to the pom.xml file.

     npm
        Print credential settings to add to the .npmrc file.
 python
        Print credential settings to add to the .pypirc and pip.conf files.

NOTES
    These variants are also available:

        $ gcloud alpha artifacts print-settings

        $ gcloud beta artifacts print-settings
```

**Comment by jamiet-msm** [comment]
I know "me too" comments are frowned upon however I just want to call out that I'm facing the same issue and I reported it over at https://stackoverflow.com/questions/68809282/invalid-repository-type-python-valid-type-is-pypi

**Comment by jamiet-msm** [comment]
> im running this command but still gettin a `invalid repository type PYTHON`
> 
> ```
> ERROR: (gcloud.alpha.artifacts.print-settings.python) Invalid repository type PYTHON. Valid type is PYPI.
> ```
> 
> But if i type pypi it doesn't work either :(

I know "me too" comments are frowned upon however I just want to call out that I'm facing the same issue as @brummetj and I reported it over at https://stackoverflow.com/questions/68809282/invalid-repository-type-python-valid-type-is-pypi

**Comment by jamiet-msm** [comment]
Until this bug is investigated it would be useful to know what `gcloud alpha artifacts print-settings python` is intended to return. The documentation:
![image](https://user-images.githubusercontent.com/79862277/129686028-e5c00bbb-7121-4b60-ac3d-60887255eb0a.png)
_https://github.com/GoogleCloudPlatform/artifact-registry-python-tools#authentication_

is, I feel, rather ambiguous about it. I *think* its suggesting that `gcloud alpha artifacts print-settings python` returns the information that should be added to `.pypirc` and/or `pip.conf` (in which case its not a big deal to write it by hand) but I'm not 100% sure that that is the case.

Some clarity about what gets returned from `gcloud alpha artifacts print-settings python` would be appreciated.

**Comment by megan-kuo** [comment]
Thanks for reporting this issue! 

We are working on a fix with an ETA of August 24th.

`gcloud artifacts print-settings python` is intended to return the configuration that should be added to the `.pypirc` and `pip.conf` files. For more detailed instructions on how to configure your repository, please take a look at this quick start [here](https://cloud.google.com/artifact-registry/docs/python/quickstart#configure)

**Comment by jamiet-msm** [comment]
Hi @megan-kuo , that's great. Thanks very much.

**Comment by megan-kuo** [comment]
Please update your gcloud version to the newest release - version 354.0.0. to see the changes. 

Thanks!
