### ISSUE TITLE
keyrings.google-artifactregistry-auth requires [re]authentication to use GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by caseydialpad** [GoogleCloudPlatform/artifact-registry-python-tools#23]
Consider the following sequences of console commands when installing with `--extra-index-url` in `requirements.txt` from GCP Artifact Registry Python repository:

``` sh
# GOOGLE_APPLICATION_CREDENTIALS already exported
python3 -m venv .venv
. .venv/bin/activate
pip install keyrings.google-artifactregistry-auth

echo "--extra-index-url 'https://gcp.private.repository/simple'

your-private-packge" > requirements.txt
pip install -r requirements.txt
```

And:

``` sh
# GOOGLE_APPLICATION_CREDENTIALS already exported
# User prompted for username and password
gcloud auth login

python3 -m venv .venv
. .venv/bin/activate
pip install keyrings.google-artifactregistry-auth

echo "--extra-index-url 'https://gcp.private.repository/simple'

your-private-packge" > requirements.txt
pip install -r requirements.txt
```

Yield the following output:
``` console
$ pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://gcp.private.repository/simple
User for gcp.private.repository:
```

In both cases, it appears that the GCP keyring is not working as expected:

``` console
$ keyring --list
keyring.backends.chainer.ChainerBackend (priority: -1)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.OS_X.Keyring (priority: 5)
```

Running `gcloud auth login`  after `pip install keyrings.google-artifactregistry-auth` allows pip to install from `gcp.private.repository` correctly without user prompts.

For clarity, the following series of commands does not lead to a user prompt and correctly installs `your-private-package`:

``` sh
# GOOGLE_APPLICATION_CREDENTIALS already exported
python3 -m venv .venv
. .venv/bin/activate
pip install keyrings.google-artifactregistry-auth

# No user prompt
gcloud auth login

echo "--extra-index-url 'https://gcp.private.repository/simple'

your-private-packge" > requirements.txt
pip install -r requirements.txt
```

Assuming `GOOGLE_APPLICATION_CREDENTIALS` points to a valid credential, is there a way for the keyring backend to work without the additional re-authentication after installing `keyrings.google-artifactregistry-auth`?

**Comment by caseydialpad** [comment]
Of additional interest, I have found `` works as expected inside a container. Consider the following Dockerfile:

``` Dockerfile
FROM python:latest

RUN python3 -m pip install keyrings.google-artifactregistry-auth

ENTRYPOINT ["python3", "-m", "pip", "install", "your-private-packge", "--extra-index-url", "https://gcp.private.repository/simple"]
```

Substituting in your own package and private repository and running the following commands:

``` sh
docker build -t pip_private .
docker run --rm -it -v "${GOOGLE_APPLICATION_CREDENTIALS}":/gcloud/creds.json -e "GOOGLE_APPLICATION_CREDENTIALS"="/gcloud/creds.json" -e "GOOGLE_CLOUD_PROJECT"="project_name" pip_private
```

Works as expected.

**Comment by megan-kuo** [comment]
Hi @caseydialpad, it looks like the package `keyrings.google-artifactregistry-auth` isn't being installed properly because the output of the command `keyring --list-backend` should include the `keyring.gauth.GooglePythonAuth` as a listed backend. 

I did try to reproduce your issue and was able to upload without the user prompt when `GOOGLE_APPLICATION_CREDENTIALS` was exported first, followed by the keyring package installation. 

Can you check that you are able to properly install our `keyrings.google-artifactregistry-auth` package in the virtual environment? You can run the command `pip show keyrings.google-artifactregistry-auth` to see if it was installed.

**Comment by caseydialpad** [comment]
Hi @megan-kuo,

When I run the following:
``` sh
python3 -m venv .venv
. .venv/bin/activate
pip install keyrings.google-artifactregistry-auth
pip show keyrings.google-artifactregistry-auth
```
I receive:
``` text
Name: keyrings.google-artifactregistry-auth
Version: 1.0.0
Summary: Keyring backend for Google Auth tokens
Home-page: https://github.com/GoogleCloudPlatform/artifact-registry-python-tools
Author: Megan Kuo
Author-email: megankuo@google.com
License: UNKNOWN
Location: /private/tmp/.venv/lib/python3.7/site-packages
Requires: requests, pluggy, google-auth, keyring
Required-by: 
```
I noticed I was using `pip-20.1.1`. Upgrading to `pip-21.3.1` resolved the issue. Although, it's not clear to me why running `gcloud auth login` would make things work when using `pip-20.1.1`.
